# Manifiesto de Aplicacion de Wordpress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
# Monta el sistema de archivos como el usuario 1001
      securityContext:
        fsGroup: 1001
# Describe que container usara el Pod
      containers:
        - image: docker.io/bitnami/wordpress-nginx:6
          name: wordpress
          env:
          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              configMapKeyRef:
                name: wpblogname
                key: name
          - name: WORDPRESS_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: wpdbhost
                key: name
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: wpdbname
                key: name
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: wpdbuser
                key: name
# Variable usando secret
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: bitnamidb
          - name: WORDPRESS_EMAIL
            value: 'omarvilera21@gmail.com'
          - name: WORDPRESS_FIRST_NAME
            value: 'Mi'
          - name: WORDPRESS_LAST_NAME
            value: 'Empresa'
# Variable usando secret
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wppass
                key: wpsecret
          - name: WORDPRESS_PLUGINS
            valueFrom:
              configMapKeyRef:
                name: wpplugins
                key: name
          - name: WORDPRESS_USERNAME
            valueFrom:
              configMapKeyRef:
                name: wpusername
                key: name
          securityContext:
            runAsUser: 1001
# Puertos del container            
          ports:
            - containerPort: 8080
              name: wordpress
# Path donde se monta el volumen de archivos              
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /bitnami/wordpress
# PVC para el almacenamiento persistente
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  serviceName: wordpress-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      securityContext:
        fsGroup: 1001      
      containers:
      - image: bitnami/mysql:latest
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
              configMapKeyRef:
                name: wpdbuser
                key: name
        - name: MYSQL_DATABASE
          valueFrom:
              configMapKeyRef:
                name: wpdbname
                key: name
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rootdb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
               name: db-secret
               key: bitnamidb
        securityContext:
          runAsUser: 1001
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /bitnami/mysql/data
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
